### ISSUE TITLE
Configuration execution fails when request body template is given as a file path.

### ISSUE THREAD

**Issue by santhanuv** [santhanuv/srotas#1]
**config.yaml**
```yaml
steps:
  - type: http
    step:
      name: "Example request"
      method: POST
      url: "/endpoint" 
      body:
        file: "requests/request.go.tmpl"
        data:
          testData: "data"
      store:
        response: "response"
      validations:
        status_code: 201
```

**Error**
"requests/request.go.tmpl" is an incomplete or empty template.

Execution fails when `body.file` is given as a file path.
